name: Build and Test #try again

on:
  workflow_dispatch:
  push:
    branches:
      - master  # Trigger on push to 'master' branch
  pull_request:
    branches:
      - master  # Trigger on pull request targeting 'master' branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use GitHub's hosted Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          cache: "maven"

      - name: Install Corepack (for Yarn and pnpm management)
        run: |
            corepack enable  # Enable Corepack, which can manage Yarn or pnpm

      - name: Install Yarn (via Corepack)
        run: corepack prepare yarn@stable --activate  # Ensures that Corepack installs the latest Yarn


      - name: Build with Maven
        run: mvn clean install -DskipTests -Dspotbugs.skip=true

      - name: Run only our tests
        run: mvn -Dtest=PartitionTest,FunctionalTest,SearchTestImproved test
